### ISSUE TITLE
Compiling under linux

### ISSUE THREAD

**Issue by Titaniumtown** [TheOpenSpaceProgram/new-ospgl#1]
How would one compile this under linux? Wouldn't a cmake file be more applicable for this project?

**Comment by jonesmz** [comment]
Agreed.

Would you be interested in submitting a pull request?

**Comment by Titaniumtown** [comment]
I don't know that much on setting up a cmake file, sorry. I'll look into and try to learn!

**Comment by jonesmz** [comment]
Please do :)

And join us on our discord channel as well.

https://discord.gg/835gGQ

**Comment by Capital-Asterisk** [comment]
I actually have a working CMake build just lying around from a few weeks ago. It's an older version and a bit messy, but it's a good start. It's pushed into the new cmake-build branch.

All of the build steps are stuffed into a single CMakeLists.txt file at the root, and some sources were modified to work with GCC. Missing dependencies were added as submodules, so remember to ` --recurse-submodules`.  It also needs GLFW 3.3 from a package manager. btw, it was built on arch.

**Comment by Titaniumtown** [comment]
Ok, thanks! (I'm on arch too)

**Comment by Titaniumtown** [comment]
I keep getting the error: `fatal error: physics/debug/BulletDebugDrawer.h: No such file or directory
   22 | #include "physics/debug/BulletDebugDrawer.h"` on compilation. Any idea why this is happening? I can't file a BulletDebugDrawer.h file anywhere!

**Comment by pufflegamerz** [comment]
I got this while trying to make:
`In file included from /home/daniel/Desktop/new-ospgl/src/util/DebugDrawer.h:7:0,
                 from /home/daniel/Desktop/new-ospgl/src/BulletExperiments.cpp:5:
/home/daniel/Desktop/new-ospgl/src/util/../assets/AssetManager.h:8:10: fatal error: filesystem: No such file or directory
`
It failed on 20%.

**Comment by Titaniumtown** [comment]
weird

**Comment by Capital-Asterisk** [comment]
delete BulletExperiments.cpp and it should work. the file is its own executable, containing a separate main function. it was taken from a time while Tatjam was in the middle of experimenting with Bullet, and the file wasn't committed yet. seems it's present in the newest commits; there's been lots of changes since then.

**Comment by Titaniumtown** [comment]
I got the cmake-build branch working on my fork (https://github.com/Titaniumtown/new-ospgl). Make sure you clone the branch "cmake-build" and not master, as I have not updated that yet.
To compile you need to do: `mkdir build && cd build && cmake .. && make -j$(expr $(nproc) \+ 1)`
After it's done compiling, you need to copy the OSPGL binary to the root of the git repo so it can access the assets.
I will make a pull request shortly, then start working on updating the cmake-build branch.

**Comment by Titaniumtown** [comment]
Pull request made: #2

**Comment by Titaniumtown** [comment]
Just wondering, is there a specific compiler and version this is supposed to compile with? on gcc8 and gcc9 I'm getting errors. (This is while I'm trying to add cmake to the master branch)

**Comment by Titaniumtown** [comment]
I keep getting this error: https://pastebin.com/YzrhfeqP
I am using gcc 9.2.1 on arch linux, I've also tried gcc 8.3.0 with the same result. Any ideas?

**Comment by tatjam** [comment]
Did you manage to fix the compiler errors? They seem to be related to the serialization macros which are very spaguetti...

**Comment by Titaniumtown** [comment]
No I have not figured it out, I am still looking into it.

**Comment by Titaniumtown** [comment]
I'm getting this: `In file included from /home/simon/new-ospgl_test/src/util/../assets/AssetManager.h:11,
                 from /home/simon/new-ospgl_test/src/util/DebugDrawer.h:7,
                 from /home/simon/new-ospgl_test/src/VehicleInWorld.cpp:3:
/home/simon/new-ospgl_test/src/universe/vessel/../element/body/config/../../../../util/serializers/glm.h: In static member function ‘static void GenericSerializer<glm::tvec2<U, glm::packed_highp> >::deserialize(glm::tvec2<U, glm::packed_highp>&, const cpptoml::table&)’:
/home/simon/new-ospgl_test/src/util/../assets/../util/SerializeUtil.h:12:25: error: expected initializer before ‘logger’
   12 | #define TOML_CHECK_FUNC logger->check_important
      |                         ^~~~~~
/home/simon/new-ospgl_test/src/util/../assets/../util/SerializeUtil.h:25:2: note: in expansion of macro ‘TOML_CHECK_FUNC’
   25 |  TOML_CHECK_FUNC(from.get_qualified_as<type>(name).operator bool(), "Data " name " of type " #type " was malformed"); \
      |  ^~~~~~~~~~~~~~~
/home/simon/new-ospgl_test/src/universe/vessel/../element/body/config/../../../../util/serializers/glm.h:22:4: note: in expansion of macro ‘SAFE_TOML_GET’
   22 |    SAFE_TOML_GET(x, "x", double);
      |    ^~~~~~~~~~~~~
/home/simon/new-ospgl_test/src/universe/vessel/../element/body/config/../../../../util/serializers/glm.h:23:18: error: ‘y’ was not declared in this scope
   23 |    SAFE_TOML_GET(y, "y", double);
      |                  ^
/home/simon/new-ospgl_test/src/util/../assets/../util/SerializeUtil.h:26:2: note: in definition of macro ‘SAFE_TOML_GET’
   26 |  target = *from.get_qualified_as<type>(name);
      |  ^~~~~~
In file included from /home/simon/new-ospgl_test/src/vehicle/part/../../assets/PartPrototype.h:3,
                 from /home/simon/new-ospgl_test/src/vehicle/part/Piece.h:12,
                 from /home/simon/new-ospgl_test/src/vehicle/part/Part.h:2,
                 from /home/simon/new-ospgl_test/src/vehicle/Vehicle.h:2,
                 from /home/simon/new-ospgl_test/src/VehicleInWorld.cpp:23:
/home/simon/new-ospgl_test/src/vehicle/part/../../assets/Model.h: At global scope:
/home/simon/new-ospgl_test/src/vehicle/part/../../assets/Model.h:120:43: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
  120 |  static constexpr char* COLLIDER_PREFIX = "col_";
      |                                           ^~~~~~
In file included from /home/simon/new-ospgl_test/src/vehicle/part/Piece.h:12,
                 from /home/simon/new-ospgl_test/src/vehicle/part/Part.h:2,
                 from /home/simon/new-ospgl_test/src/vehicle/Vehicle.h:2,
                 from /home/simon/new-ospgl_test/src/VehicleInWorld.cpp:23:
/home/simon/new-ospgl_test/src/vehicle/part/../../assets/PartPrototype.h:98:40: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   98 |  static constexpr char* PIECE_PREFIX = "p_";
      |                                        ^~~~
/home/simon/new-ospgl_test/src/vehicle/part/../../assets/PartPrototype.h:99:37: warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   99 |  static constexpr char* ROOT_NAME = "p_root";
      |                                     ^~~~~~~~
/home/simon/new-ospgl_test/src/VehicleInWorld.cpp: In function ‘int main()’:
/home/simon/new-ospgl_test/src/VehicleInWorld.cpp:120:3: error: ‘BulletDebugDrawer’ was not declared in this scope; did you mean ‘DebugDrawer’?
  120 |   BulletDebugDrawer* bullet_debug_drawer = new BulletDebugDrawer();
      |   ^~~~~~~~~~~~~~~~~
      |   DebugDrawer
/home/simon/new-ospgl_test/src/VehicleInWorld.cpp:120:22: error: ‘bullet_debug_drawer’ was not declared in this scope; did you mean ‘debug_drawer’?
  120 |   BulletDebugDrawer* bullet_debug_drawer = new BulletDebugDrawer();
      |                      ^~~~~~~~~~~~~~~~~~~
      |                      debug_drawer
/home/simon/new-ospgl_test/src/VehicleInWorld.cpp:120:48: error: expected type-specifier before ‘BulletDebugDrawer’
  120 |   BulletDebugDrawer* bullet_debug_drawer = new BulletDebugDrawer();
      |                                                ^~~~~~~~~~~~~~~~~`

**Comment by Titaniumtown** [comment]
I haven't tested your recent commits on the cmake-build branch, I am cloning it now. I'll inform you if it works! :)

**Comment by Titaniumtown** [comment]
Is there a specific compiler I should be using? I keep getting errors related to "PartViewer.h" and refrencing "BulletDebugDrawer". Any ideas?

**Comment by tatjam** [comment]
Accepted the pull request, does it work now?

**Comment by tatjam** [comment]
Everything should work now, BulletDebugDrawer was not included into git for some reason...

**Comment by Titaniumtown** [comment]
I got this error: `/home/simon/new-ospgl/src/physics/debug/BulletDebugDrawer.h:27:87: error: no match for  operator*’ (operand types are ‘glm::dvec3’ {aka ‘glm::tvec3<double, glm::packed_highp>’} and ‘btScalar’ {aka ‘float’})` I'm using gcc 9.2.1 and I am on arch linux.

**Comment by pufflegamerz** [comment]
I am still stuck on this: 
`
/home/daniel/Desktop/new-ospgl/src/util/../assets/AssetManager.h:8:10: fatal error: filesystem: No 

such file or directory

 #include <filesystem>

          ^~~~~~~~~~~~

compilation terminated.


`

**Comment by Titaniumtown** [comment]
You need to compile on gcc 8+

**Comment by Titaniumtown** [comment]
I'm also getting errors like `error: stray ‘\342’ in program
   17 | void GroundShape::processAllTriangles(btTriangleCallback* callback, const btVector3& aabb_b�[m, const btVector3& aabb_b₁) const`

**Comment by tatjam** [comment]
Oh that's because I have used unicode in that file! Does gcc have an option to enable it? Otherwise I could simply remove it (I was playing around with the Julia language at the time and it uses a very easy system to input unicode characters, which I replicated on the EasyUnicode auto-hotkey script)

**Comment by tatjam** [comment]
gcc seems to have only recently started supporing extended character sets:
https://stackoverflow.com/questions/12692067/and-other-unicode-characters-in-identifiers-not-allowed-by-g

So I will simply remove these characters to make it easier to compile.

**Comment by Titaniumtown** [comment]
Ok, that works now, but now i'm getting the error: `error: no match for  operator*’ (operand types are ‘glm::dvec3’ {aka ‘glm::tvec3<double, glm::packed_highp>’} and ‘btScalar’ {aka ‘float’})
   27 | dd_line(to_dvec3(PointOnB), to_dvec3(PointOnB) + to_dvec3(normalOnB) * distance, to_vec3(color));
      |                                                  ~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~
      |                                                          |             |
      |                                                          |             btScalar {aka float}
      |                                                          glm::dvec3 {aka glm::tvec3<double, glm::packed_highp>}
`

**Comment by Titaniumtown** [comment]
Any idea why that may be happening?

**Comment by tatjam** [comment]
Oh that's a bullet error, you need to make sure it's compiled with doubles. I will upload the modified source, as that's not the only change, some small fixes are required in order for it to allow planetary-sized colliders.

**Comment by Titaniumtown** [comment]
How would I compile it with doubles?

**Comment by tatjam** [comment]
You need the preprocessor directive 'BT_USE_DOUBLE_PRECISION' to be defined in btScalar.h

**Comment by tatjam** [comment]
https://github.com/TheOpenSpaceProgram/ospgl-bullet

There we go, it should compile fine with CMake! (Took surprisingly long to upload, git doesn't seem to like very big commits)

**Comment by Titaniumtown** [comment]
Made pull request #4, ospgl runs fine for me now!

**Comment by tatjam** [comment]
Awesome!

**Comment by Titaniumtown** [comment]
Oh wait, shouldn't we merge this with the master branch?

**Comment by Titaniumtown** [comment]
I created a pull request related to my previous comment: #5

**Comment by Titaniumtown** [comment]
Since my pull requests got merged, shouldn't the cmake-build branch be deleted?

**Comment by pufflegamerz** [comment]
Any idea on why this is happening: https://pastebin.com/kMY2Rym3

I'm trying to build on Debian 10.

**Comment by Titaniumtown** [comment]
what compiler are you using?

**Comment by pufflegamerz** [comment]
@Titaniumtown gcc version 8.3.0

**Comment by Titaniumtown** [comment]
use gcc 9, that's what I'm using and I encountered issues with anything below that.

**Comment by pufflegamerz** [comment]
Thanks, I'll try that.

**Comment by Titaniumtown** [comment]
np, keep me posted

**Comment by jonesmz** [comment]
The pastebin looks like the -lstdc++fs flag isn't being provided

**Comment by pufflegamerz** [comment]
> -lstdc++fs flag

How do I use that flag? Sorry, I know nothing about C++, Cmake,

**Comment by Titaniumtown** [comment]
@pufflegamerz It will be included when #10 gets merged.

An explanation of what that means:
'target_link_libraries' works like this: Say you have a project named 'foo' and you need to include library 'bar' and the output binary is named 'cool-binary' you would have at the end of your CMakeLists.txt `target_link_libraries(cool-binary bar)`. The argument the linker is provided when that point of the CMakeLists.txt file is reached is '-lbar'. 
Bringing that back to my pull request, the output binary 'OSPGL' is being linked with the option '-lstdc++fs' when you add 'stdc++fs' to the target_link_libraries section at the end of your CMakeLists.txt, which my pull request does.
Hope that cleared that up!

**Comment by pufflegamerz** [comment]
@Titaniumtown Thanks for explaining!

**Comment by Titaniumtown** [comment]
Yea, no problem! :)

**Comment by Titaniumtown** [comment]
Forgot to close this issue, as the issue is now solved.
