### ISSUE TITLE
Universe.h issue

### ISSUE THREAD

**Issue by Titaniumtown** [TheOpenSpaceProgram/new-ospgl#14]
I get the following error during compilation:
`/home/simon/new-ospgl/src/universe/Universe.h:83:13: error: parameter packs not expanded with ‘...’:
   83 |  T* n_ent = new T(args);
      |             ^~~~~~~~~~~`

**Comment by jonesmz** [comment]
Change
```
template<typename T, typename... Args> 
T* create_entity(Args... args);
```
to
```
template<typename T, typename... Args> 
T* create_entity(Args... args);
```
and
```
template<typename T, typename ...Args>
inline T* Universe::create_entity(Args... args)
```
to
```
template<typename T, typename ...Args>
inline T* Universe::create_entity(Args && ... args)
```
and
	`T* n_ent = new T(args);`
to
	`T* n_ent = new T(std::forward<Args>(args)...);`

**Comment by tatjam** [comment]
Agh why is Visual Studio so permissive... Will push the fix next commit

**Comment by jonesmz** [comment]
https://docs.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance?view=vs-2019

**Comment by tatjam** [comment]
Well, Visual Studio actually reports these errors, but you need to call the code that causes them somewhere. 

Enabling /permissive- doesn't seem to change that behaviour, but it throws some warnings on the dependency libraries.

**Comment by tatjam** [comment]
It's fixed now, forgot to close the issue!
