### ISSUE TITLE
Godot engine?

### ISSUE THREAD

**Issue by Titaniumtown** [TheOpenSpaceProgram/new-ospgl#15]
Should this project be in the godot engine instead? Just thought of this.

**Comment by jonesmz** [comment]
No. Godot refuses to use modern c++. Its garbage.

**Comment by tatjam** [comment]
I don't personally like Godot either, it may have improved over time but when I used it it felt slow and awkward (for 3D games, the 2D mode is way better). Also, we would probably need to use hacks similar to KSP running on Unity to get the renderer to work on big distances.

**Comment by Titaniumtown** [comment]
oh ok, I didnt know that. Thanks for the insight!
