### ISSUE TITLE
add #include <cstdint> to profiler.h

### ISSUE THREAD

**Issue by tigercoding56** [TheOpenSpaceProgram/new-ospgl#65]
when compiling cmake errored out and told me to add #include <cstdint> to src/util/profiler.h doing this made new-ospgl compile  i am not sure why it was not there to begin with so i think it is a linux / vs windows issue and may need to be configured using the makefiles  (i am too stupid for that so i just made a issue)

**Comment by tatjam** [comment]
Yup it's likely the weird conventions on when cstdint is included by default. I'm going to add the include to the file!
