### ISSUE TITLE
Don't set link flags globally, set it per target with TARGET_LINK_LIBRARIES function

### ISSUE THREAD

**Issue by jonesmz** [TheOpenSpaceProgram/new-ospgl#8]
https://github.com/TheOpenSpaceProgram/new-ospgl/blob/d417326f4f6b502bc77934dbfc50995267ff458e/CMakeLists.txt#L20

**Comment by Titaniumtown** [comment]
#10 addresses this issue; once it's merged, this issue can be resolved.

**Comment by tatjam** [comment]
Merged!
