### ISSUE TITLE
Missing stdc++fs library include

### ISSUE THREAD

**Issue by jonesmz** [TheOpenSpaceProgram/new-ospgl#9]
https://github.com/TheOpenSpaceProgram/new-ospgl/blob/d417326f4f6b502bc77934dbfc50995267ff458e/CMakeLists.txt#L20

Add it with TARGET_LINK_LIBRARIES(targetnamehere stdc++fs)

**Comment by Titaniumtown** [comment]
I created #10 that will address this issue.
